/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  totpSecret?: string | null;
  totpEnabled?: boolean | null;
  totpPendingSecret?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  layout: (
    | {
        video?: (string | null) | Media;
        title: string;
        subtitle?: string | null;
        buttonText?: string | null;
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        image: string | Media;
        title: string;
        description: string;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'highPerformance';
      }
    | {
        title?: string | null;
        logos?:
          | {
              logo: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustedCompanies';
      }
    | {
        title?: string | null;
        description?: string | null;
        services?:
          | {
              title: string;
              description?: string | null;
              icon: string | Media;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mainServices';
      }
    | {
        heading: string;
        subHeading?: string | null;
        items?:
          | {
              title: string;
              highLights?: string | null;
              image: string | Media;
              description?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dataCenter';
      }
    | {
        heading: string;
        subHeading?: string | null;
        items?:
          | {
              title: string;
              description?: string | null;
              image: string | Media;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deploymentReady';
      }
    | {
        heading: string;
        subHeading?: string | null;
        items?:
          | {
              title: string;
              description?: string | null;
              image: string | Media;
              icon: string | Media;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'customHardwarePortfolio';
      }
    | {
        heading: string;
        title: string;
        highlightText?: string | null;
        subText?: string | null;
        buttonText?: string | null;
        buttonLink?: string | null;
        video: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyChooseUs';
      }
    | {
        heading?: string | null;
        description?: string | null;
        cards?:
          | {
              title: string;
              description?: string | null;
              image: string | Media;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        buttonText?: string | null;
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'researchPortfolio';
      }
    | {
        heading?: string | null;
        description?: string | null;
        posts?:
          | {
              title: string;
              source?: string | null;
              date?: string | null;
              image: string | Media;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'smarterDecisions';
      }
    | {
        heading?: string | null;
        description?: string | null;
        faqs?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        title: string;
        backgroundImage: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutBanner';
      }
    | {
        heading: string;
        badgeText: string;
        description: string;
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ourMission';
      }
    | {
        heading: string;
        description: string;
        members?:
          | {
              name: string;
              role: string;
              content1?: string | null;
              content2?: string | null;
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        stats?:
          | {
              value: string;
              title: string;
              description?: string | null;
              icon: string | Media;
              id?: string | null;
            }[]
          | null;
        speed?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'whoWeAre';
      }
    | {
        heading: string;
        subheading?: string | null;
        members?:
          | {
              name: string;
              role: string;
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'talentedTeam';
      }
    | {
        heading: string;
        subheading: string;
        steps?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stepByStep';
      }
    | {
        heading: string;
        items?:
          | {
              title: string;
              source?: string | null;
              date?: string | null;
              image: string | Media;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'insights';
      }
    | {
        heading?: string | null;
        subheading?: string | null;
        quote?: string | null;
        authorName?: string | null;
        authorRole?: string | null;
        authorImage?: (string | null) | Media;
        formTitle?: string | null;
        formDescription?: string | null;
        subjects?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        heading?: string | null;
        description?: string | null;
        contacts?:
          | {
              image?: (string | null) | Media;
              name?: string | null;
              role?: string | null;
              title?: string | null;
              phone?: string | null;
              email?: string | null;
              id?: string | null;
            }[]
          | null;
        locations?:
          | {
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'officeLocations';
      }
    | {
        title: string;
        type: 'software' | 'hardware';
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        patentNumbers?:
          | {
              number?: string | null;
              id?: string | null;
            }[]
          | null;
        highlights?:
          | {
              text: string;
              variant: 'primary' | 'secondary' | 'accent' | 'muted';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'patentCards';
      }
    | {
        title: string;
        description: string;
        image: {
          image: string | Media;
        };
        highlights: {
          text: string;
          variant: 'primary' | 'secondary' | 'accent' | 'muted';
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'keyNotes';
      }
    | {
        title: string;
        subtitle: string;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        bannerImage: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'blockchainBanner';
      }
    | {
        heading: string;
        subheading: string;
        image: string | Media;
        cards?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'revolution';
      }
    | {
        heading: string;
        expoCards?:
          | {
              title: string;
              subtitle: string;
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ampereExpo';
      }
    | {
        heading: string;
        subheading: string;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        image: string | Media;
        stats?:
          | {
              title: string;
              description: string;
              icon: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'weBuild';
      }
    | {
        heading: string;
        locations?:
          | {
              location: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'innovation';
      }
    | {
        heading: string;
        testimonials?:
          | {
              quote: string;
              icon?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'services';
      }
    | {
        heading: string;
        subheading: string;
        ratingText?: string | null;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        features?:
          | {
              title: string;
              description: string;
              image?: (string | null) | Media;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'transformingBusiness';
      }
    | {
        heading: string;
        description: string;
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'decentralizingFinance';
      }
  )[];
  meta?: {
    /**
     * Title shown in search engine results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Description shown in search engine results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    image?: (string | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages submitted via the Contact Us form on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  status?: ('new' | 'in_progress' | 'resolved' | 'spam') | null;
  /**
   * Internal notes — not visible to the user.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  totpSecret?: T;
  totpEnabled?: T;
  totpPendingSecret?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        banner?:
          | T
          | {
              video?: T;
              title?: T;
              subtitle?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        highPerformance?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        trustedCompanies?:
          | T
          | {
              title?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mainServices?:
          | T
          | {
              title?: T;
              description?: T;
              services?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dataCenter?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              items?:
                | T
                | {
                    title?: T;
                    highLights?: T;
                    image?: T;
                    description?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        deploymentReady?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        customHardwarePortfolio?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyChooseUs?:
          | T
          | {
              heading?: T;
              title?: T;
              highlightText?: T;
              subText?: T;
              buttonText?: T;
              buttonLink?: T;
              video?: T;
              id?: T;
              blockName?: T;
            };
        researchPortfolio?:
          | T
          | {
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        smarterDecisions?:
          | T
          | {
              heading?: T;
              description?: T;
              posts?:
                | T
                | {
                    title?: T;
                    source?: T;
                    date?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              description?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutBanner?:
          | T
          | {
              title?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        ourMission?:
          | T
          | {
              heading?: T;
              badgeText?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        whoWeAre?:
          | T
          | {
              heading?: T;
              description?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    content1?: T;
                    content2?: T;
                    image?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              speed?: T;
              id?: T;
              blockName?: T;
            };
        talentedTeam?:
          | T
          | {
              heading?: T;
              subheading?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepByStep?:
          | T
          | {
              heading?: T;
              subheading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    source?: T;
                    date?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              subheading?: T;
              quote?: T;
              authorName?: T;
              authorRole?: T;
              authorImage?: T;
              formTitle?: T;
              formDescription?: T;
              subjects?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        officeLocations?:
          | T
          | {
              heading?: T;
              description?: T;
              contacts?:
                | T
                | {
                    image?: T;
                    name?: T;
                    role?: T;
                    title?: T;
                    phone?: T;
                    email?: T;
                    id?: T;
                  };
              locations?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        patentCards?:
          | T
          | {
              title?: T;
              type?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              patentNumbers?:
                | T
                | {
                    number?: T;
                    id?: T;
                  };
              highlights?:
                | T
                | {
                    text?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        keyNotes?:
          | T
          | {
              title?: T;
              description?: T;
              image?:
                | T
                | {
                    image?: T;
                  };
              highlights?:
                | T
                | {
                    text?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blockchainBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonLink?: T;
              bannerImage?: T;
              id?: T;
              blockName?: T;
            };
        revolution?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ampereExpo?:
          | T
          | {
              heading?: T;
              expoCards?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        weBuild?:
          | T
          | {
              heading?: T;
              subheading?: T;
              buttonLabel?: T;
              buttonLink?: T;
              image?: T;
              stats?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        innovation?:
          | T
          | {
              heading?: T;
              locations?:
                | T
                | {
                    location?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        transformingBusiness?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ratingText?: T;
              buttonLabel?: T;
              buttonLink?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        decentralizingFinance?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  menu?:
    | {
        name?: string | null;
        path?: string | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    href: string;
    /**
     * Your Calendly scheduling link (e.g. https://calendly.com/your-name/30min). When set, the CTA button will open a Calendly popup instead of navigating to a URL.
     */
    calendlyUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  menu?:
    | {
        name?: string | null;
        path?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name?: string | null;
        icon?: (string | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  menu?:
    | T
    | {
        name?: T;
        path?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        calendlyUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  menu?:
    | T
    | {
        name?: T;
        path?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        icon?: T;
        url?: T;
        id?: T;
      };
  email?: T;
  phone?: T;
  address?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}